### ISSUE TITLE
Load balancer must check if the server in the provided pool is online before sending a request

### ISSUE THREAD

**Issue by SiNONiMiTY** [mercurius-js/mercurius-gateway#64]
Title says

I am encountering a scenario where I provide 2 URLs for a single subgraph in an array form

```
const gateway = Fastify()
gateway.register(mercuriusGateway, {
    gateway: {
        services: [
            {
                "name": "user",
                "url": [
                "http://endpoint1:4001/graphql",
                "http://endpoint2:4001/graphql"
                ],
                "schema": "type Query { id: ID }"
            }
        ]
    }
})
```

endpoint2 is intentionally taken down and only endpoint1 is working, however,
when sending queries on the gateway, I am occassionally receiving errors about ECONNREFUSED on endpoint2.

The load balancing mechanism should first do a test ping if the host is reachable before sending a request.

**Comment by mcollina** [comment]
Unfortunately it's a bit more complex than sending a "ping", as those errors come from existing sockets that are truncated.

How are you shutting down your upstreams servers? Are they closing gracefully or are they crashing?

**Comment by SiNONiMiTY** [comment]
> Unfortunately it's a bit more complex than sending a "ping", as those errors come from existing sockets that are truncated.
> 
> How are you shutting down your upstreams servers? Are they closing gracefully or are they crashing?

Starting the gateway with only one online subgraph out of the two provided

**Comment by mcollina** [comment]
Thanks, that helps!

I think there is a bug in undici [`BalancedPool`](https://github.com/nodejs/undici/blob/main/lib/balanced-pool.js) that routes requests to an upstream even if it could not connect there, and it does not retry/send it elsewhere in case it fails to connect. Things stabilizes over time because of `BalancedPool` algorithm, so only a few number of requests would fail.

The bad news is that I don't have time right now to fix it there.

**Comment by SiNONiMiTY** [comment]
> Thanks, that helps!
> 
> I think there is a bug in undici [`BalancedPool`](https://github.com/nodejs/undici/blob/main/lib/balanced-pool.js) that routes requests to an upstream even if it could not connect there, and it does not retry/send it elsewhere in case it fails to connect. Things stabilizes over time because of `BalancedPool` algorithm, so only a few number of requests would fail.
> 
> The bad news is that I don't have time right now to fix it there.

Yes! I noticed that the balancing algorithm eventually only selects the online server after sending some requests.

**Comment by Bugs5382** [comment]
@mcollina  This issue is more relevant in 3.0.0 cause I am now getting tons of this error on the controller talking to the GW in Kube. I never had this problem, and suddenly, I am getting timeouts too often. 

```
[16:36:30.017] INFO (21): Symbol(FEDERATED_ERROR)
    reqId: "req-ko"
    err: {
      "type": "GraphQLError",
      "message": "Symbol(FEDERATED_ERROR)",
      "stack":
          Error: Symbol(FEDERATED_ERROR)
              at request (/home/node/app/node_modules/@mercuriusjs/gateway/lib/gateway/request.js:67:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.sendRequest (/home/node/app/node_modules/@mercuriusjs/gateway/lib/gateway/request.js:80:45)
              at async Object.QuerystatisticsDeviceTypeResolver (/home/node/app/node_modules/@mercuriusjs/gateway/lib/gateway/make-resolver.js:628:24)
      "locations": [
        {
          "line": 22,
          "column": 3
        }
      ],
      "path": [
        "rawDataCategory"
      ],
      "extensions": {
        "errors": [
          {
            "errno": -111,
            "code": "ECONNREFUSED",
            "syscall": "connect",
            "address": "10.111.16.199",
            "port": 3000
          }
        ]
      }
    }
```

This is what I get, and it fails at different paths. Running the graphql that it's connected to manually works without an issue. A few seconds later I get:

```
[16:38:44.574] INFO (21): Symbol(FEDERATED_ERROR)
    reqId: "req-li"
    err: {
      "type": "GraphQLError",
      "message": "Symbol(FEDERATED_ERROR)",
      "stack":
          Error: Symbol(FEDERATED_ERROR)
              at request (/home/node/app/node_modules/@mercuriusjs/gateway/lib/gateway/request.js:67:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.sendRequest (/home/node/app/node_modules/@mercuriusjs/gateway/lib/gateway/request.js:80:45)
              at async Object.QuerystatisticsDevicePrintStatusResolver (/home/node/app/node_modules/@mercuriusjs/gateway/lib/gateway/make-resolver.js:628:24)
      "locations": [
        {
          "line": 16,
          "column": 3
        }
      ],
      "path": [
        "statisticsDevicePrintStatus"
      ],
      "extensions": {
        "errors": [
          {
            "errno": -111,
            "code": "ECONNREFUSED",
            "syscall": "connect",
            "address": "10.111.16.199",
            "port": 3000
          }
        ]
      }
    }
```

Going to revert this plugin before 3.0.0 see if there is an issue.
